export const SCREENS = {
  BOARDING: 'Boarding',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOME_TABS: 'HomeTabs',
  HOME: 'Home',
  FAVORITES: 'Favorites',
  PROFILE: 'Profile',
  PRODUCT_DETAIL: 'ProductDetail',
  CART: 'Cart',
  CHECKOUT: 'Checkout',
  SUCCESS: 'Success',
  SHIPPING_ADDRESS: 'ShippingAddress',
  ADD_OR_EDIT_ADDRESS: 'AddOrEditAddress',
} as const;
